### PR TITLE
Added graphics for activated and deactivated hypergate models.

### PR DESCRIPTION
**Pull request by V-ktor**
Added graphics for activated and deactivated hypergate models.

### CODE REVIEW

**Comment by bobbens** [comment]
Would it be possible to also get the mask you showed me on discord too? Would like to try implementing your shader and looking at them in-game. Thanks!

**Comment by V-ktor** [comment]
Here it is. I guess you want to replace the texture by a noise generator, right?

**Comment by bobbens** [comment]
> Here it is. I guess you want to replace the texture by a noise generator, right?

Yes, but I will try with your texture from discord first, and then see if I can cook up something similar.

**Comment by bobbens** [comment]
Looks good, thanks!

**Pull request merged**
