### PR TITLE
Planets and Soromids

### PR DESCRIPTION
**Pull request by theElerd**

### CODE REVIEW

**Comment by bobbens** [comment]
Looks great! Some comments:
1. It could be just me but the planets look a bit flat. Maybe they need more shading?
2. `gfx/portraits/soromid/soromid_heavy_civilian_2.webp` is missing I think
3. I think the portraits should be a bit more zoomed in on the face area. I think they will appear much smaller in-game than other characters (unless you want to emphasize that they have tiny bodies compared to "standard" humans)

**Comment by theElerd** [comment]
1. I was contemplating adding lights to the dark side to show more of the curvature.
I'll try to change the lighting to make it less flat.

2. Yeah that's weird. I think I may have removed it unintentionally. I'll add it in the fix for the first point

3. The zoom out is so you can see they're on their tail, but I think your right. I'll re-render them zoomed in.

**Comment by theElerd** [comment]
All Done.

Let me know if there's anything missing

**Comment by bobbens** [comment]
(just in case repeating discord message)
Could you create a new branch off of master, add your new files and changes, and force push over the PR? If you change files and such, the git repository bloats pretty bad, and we want to avoid that if possible (the reason for having artwork in a separate git repository is we can nuke it and redo it if bloat gets too bad).

**Pull request closed without merging**
