### PR TITLE
Made some missile files from stuff I found

### PR DESCRIPTION
**Pull request by ghost**
From the depths of Naev's 3d art files:

Imperator from modifiers.blend
imperator launcher from modifiers.blend
headhunter launcher a mix of headhunter.blend, bansheelauncher.blend, and modifiers.blend

### CODE REVIEW

**Comment by bobbens** [comment]
Some comments (also left on discord):
- the imperator stuff looks really good, however, the in-game sprite seems to be very blurry and possibly too big.
- I would recommend rerendering the in-game sprite at 4x the target resolution, then resize with the `resize.sh` script which basically does (`$RAWFILE` is the input and `$OUTFILE` is the output):
```sh
TMPFILE=`mktemp --suffix .png`
convert -colorspace LAB -resize $SIZE -sharpen 1 -colorspace sRGB "$RAWFILE" "$TMPFILE" &> /dev/null
cwebp -lossless -z 9 "$TMPFILE" -o "$OUTFILE"
```
- Could you add licensing information for both the sound and the images in `gfx/ARTWORK_LICENSE.yaml` and `snd/SOUND_LICENSE.yaml`?
- Regarding the headhunter turret, the base and the launcher itself seem to not really match well at all and it's hard to tell it's the same thing. I'm also not a really big fan of the launcher part itself, it looks fairly unpractical and the light blue is a bit weird. Could you please remove this turret from the PR and force push?

**Comment by bobbens** [comment]
To avoid bloat (all binary data changes are saved in the GIT repo), could you redo the commits? You don't have to redo the PR, but copy the images somewhere, reset the repo to main, then recommit it in one commit.

**Comment by ghost** [comment]
Yeah, sorry about that.

**Comment by bobbens** [comment]
Looks good, thanks!

**Pull request merged**
