### PR TITLE
Create cryogenic_repair_nanobots.webp

### PR DESCRIPTION
**Pull request by ghost**
Not really good, but it's better than a placeholder image.

### CODE REVIEW

**Comment by bobbens** [comment]
I see you changed the image. I sort of like the original one a bit more. Given that they are nanobots, something that looks like it was taken with an electronic scanning microscope would look better. Actually, now that I think about it, what about just using the image from https://en.wikipedia.org/wiki/Scanning_electron_microscope#/media/File:Misc_pollen.jpg ?
EMS pollen

**Comment by ghost** [comment]
I would have made it better, but gimp was refusing to cooperate.

**Comment by bobbens** [comment]
Could you add author information too please?

**Comment by bobbens** [comment]
Looks good, thanks!

**Pull request closed without merging**
